project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: annex.qmd
    - notebook: visuals.qmd

format:
  html:
    page-layout: full
    toc-location: left
    html-math-method: katex
    theme: minty
    toc: true
    number-sections: true
    comments:
      hypothesis: true
  docx:
    reference-doc: custom-reference-doc.docx
    toc: false
    number-sections: true
    default-image-extension: svg
    fig-format: svg
  jats: default

  # (other formats)
  # pdf: default

author: #"Sarah HUET, Clélia SIRAMI, Abdoul DIALLO, Julie REGOLO, Ainhoa IHASUSTA, Ludovic ARNAUD, Valentin BELLASSEN"
  - name: Sarah HUET
    orcid: 0000-0002-5449-6959
    corresponding: TRUE
    email: sarah.huet@inrae.fr
    roles:
      - Model
      - Manuscript writting and editing
    affiliation:
      - CESAER UMR 1041, INRAE/Institut Agro/Université Bourgogne Franche-Comté, Dijon, France
  - name: Clélia SIRAMI
    orcid: 0000-0003-1741-3082
    email: clelia.sirami@inrae.fr
    affiliation:
      - Dynafor UMR 1201, INRAE/Université de Toulouse, Castanet-Tolosan, France
  - name: Abdoul DIALLO
    orcid: 0000-0003-0350-8144
    email: abdoul.diallo@inrae.fr
    affiliation:
      - CESAER UMR 1041, INRAE/Institut Agro/Université Bourgogne Franche-Comté, Dijon, France
  - name: Julie REGOLO
    orcid: 0009-0005-9962-4300
    email: julie.regolo@inrae.fr
    affiliation:
      - US-ODR, INRAE, Auzeville-Tolosane, France
  - name: Ainhoa IHASUSTA
    email: ainhoa.ihasusta@inrae.fr
    affiliation:
      - CESBIO UMR 5126, Université de Toulouse/CNES/CNRS/INRAE/IRD/UPS, Toulouse, France
  - name: Ludovic ARNAUD
    orcid: 0000-0002-6106-7589
    email: ludovic.arnaud@inrae.fr
    affiliation:
      - CESBIO UMR 5126, Université de Toulouse/CNES/CNRS/INRAE/IRD/UPS, Toulouse, France
  - name: Valentin BELLASSEN
    orcid: 0000-0001-8581-2814
    email: valentin.bellassen@inrae.fr
    affiliation:
      - CESAER UMR 1041, INRAE/Institut Agro/Université Bourgogne Franche-Comté, Dijon, France
#date: "`r format(Sys.time(), '%B %d, %Y')`"

keywords: certified food, farming practices, biodiversity, environmental footprint, agriculture sustainability
date: last-modified
bibliography: references.bib
#csl: ecological-economics.csl


execute:
  freeze: true



